apps/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns =[
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment')
]

study_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls)
]

apps/articles/models.py
import datetime
from django.db import models
from django.utils import timezone


class Article(models.Model):
    title = models.CharField('Article Title', max_length=255, null=False)
    content = models.TextField('Article Content',  null=False)
    pub_date = models.DateTimeField('Article Publish Date', null=False)

    def __str__(self):
        return self.title

    def was_publish_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_name = models.CharField('Comment author name', max_length=80, null=False)
    comment_text = models.CharField('Comment text', max_length=255, null=False)

    def __str__(self):
        return self.author_name

apps/users/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser
from .seo import CustomUserManager


class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField('username', max_length=50, unique=False)
    email = models.EmailField('email address', unique=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    is_Contentmaker = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    object = CustomUserManager()

    def __str__(self):
        return f'{self.email}'


class Reader(MyUser):
    name = models.CharField("user name", max_length=70, unique=False, null=False, blank=False)


class Contentmaker(MyUser):
    name = models.CharField("user name", max_length=70, unique=False, null=False, blank=False)

apps/articles/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Article


latest_articles_list = Article.objects.order_by('-pub_date')[:5]


def index(request):
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Post not found")

    latest_comment_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'articles/detail.html', {'article': a, 'latest_comment_list': latest_comment_list})



def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except Article.DoesNotExist:  # Используйте более точное исключение
        raise Http404("Post not found")

    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect(reverse('articles:detail', args=(article_id,)))

apps/users/views.py
from django.shortcuts import render

# Create your views here.

templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Web {% endblock %}</title>
</head>
<body>

    {% block content %}{% endblock %}

</body>
</html>

templates/articles/detail.html
{% extends 'articles/base.html' %}

{%  block title %}{{ article.title }}{% endblock %}

{% block content %}

<h2>{{ article.title }}</h2>

<p>{{ article.content }}</p>

<em>{{ article.pub_date }}</em>

<hr>

{% if latest_comment_list %}

    {% for c in latest_comment_list %}
        <p>
            <strong>{{ c.author_name }}</strong>
            <p>{{ c.comment_text }}</p>
        </p>
    {% endfor %}

{% else %}
Комментарии не найдены. станьте первым =)
{% endif %}

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required="" placeholder="Текс Комментария" cols="30" rows="10"></textarea><br>

    <button type="submit">Оставить комментарий</button>
</form>

{% endblock %}

templates/articles/list.html
{% extends 'articles/base.html' %}

{%  block title %}Last Posts{% endblock %}

{% block content %}

    {% if latest_articles_list %}

        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{ a.title }}</a>
        {% endfor %}

    {% else %}
        Статьи не найдены =(
    {% endif %}

{% endblock %}